apiVersion: v1
kind: Service
metadata:
  namespace: karsajobs-ns # using namespace
  name: mongo
  labels:
    app: mongo
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    app: mongo
    tier: backend
  clusterIP: None