apiVersion: v1
kind: Service
metadata:
  namespace: karsajobs-ns # using namespace
  name: karsajobs
  labels:
    app: karsajobs
spec:
  type: NodePort # using node port
  selector:
    app: karsajobs 
  ports:
  - port: 8080 # select port